### ISSUE TITLE
Rubric score

### ISSUE THREAD

**Issue by sen1** [sarahschofield120/sql-from-scratch#2]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* 4 (Exceeds Expectations)
* Good job. Queries worked as expected.
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* 4 (Exceeds Expectations)
* Queries were accurate.
 
### Criteria 3: Query Formatting
* 4 (Exceeds Expectations)
* Nice formatting.
 
### Criteria 4: Understanding underlying concepts and terminology
* 4 (Exceeds Expectations)
* You got it.

 ### Overall Score: 16/16
Really liked your presentation. Especially the funnel diagram with 3 and 5 tries results in purchases. Very informative. Excellent work. 👏

**Comment by sarahschofield120** [comment]
Thank you!
